module.exports = {
  productsNodes: '.resultList > .product',
  productTitle: '.productTitle',
  productLink: '.productTitle > a',
  cookiesButton: 'button#onetrust-accept-btn-handler',
  addToBasket: '#product-actions div[data-component="add-to-basket-button-wrapper"] > button',
  continueToBasket: '.dc-popup-overlay button[data-interaction="Continue to basket"]',
  goToCheckout: 'div[data-component="OrderSummary"] > button',
  useCurrentLocation: 'div[data-component="GeolocationButton"] > button',
  locationInput: 'div[data-component="PostCodeChecker"] > form > input',
  freeDeliveryButton: 'div[data-component="DeliverySlotStandard"] button',
  emailInput: 'input[data-qa="CustomInput_email"]',
  emailContinueButton: 'form[data-di-form-id="email"] > button',
  formTitle: 'div[data-qa="d-title"] input',
  formFirstName: 'input[name="fname"]',
  formLastName: 'input[name="lname"]',
  formPhoneNumber: 'input[name="country-code phone"]',
  formAddress1: 'input[name="address"]',
  formAddress2: 'input[name="addressOpt"]',
  formCity: 'input[name="city"]',
  formCountry: 'input[name="countyOpt"]',
  formSubmitButton: 'form#addresses > button',
  creditCardButton: 'div[data-element="PaymentMethodsButtons"] > div[data-component="CardPayment"] > button',
  cardNumberInput: 'input#cardNumber',
  cardNameInput: 'input#cardholderName',
  cardExpiryMonthInput: 'input#expiryMonth',
  cardExpiryYearInput: 'input#expiryYear',
  cardSecurityInput: 'input#securityCode',
  cardPayButton: 'input.btn-make-payment',
};
